version: '3'

services:
  database:
    restart: always
    image: postgres:latest
    ports:
      - 5433:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD:

volumes:
  pgdata:
    driver: local